###############################################################
# OUTPUT: azure_names
# Description: All names from Azure official naming module
# Structure: Map of resource types to their generated names
# Usage: module.naming.azure_names.resource_group
# Example: "rg-neko-prod-weu-abc123"
###############################################################
output "azure_names" {
  description = "Names generated by Azure official naming module"
  value = var.use_azure_naming_module ? {
    resource_group              = module.azure_naming.resource_group.name
    resource_group_unique       = module.azure_naming.resource_group.name_unique
    virtual_network             = module.azure_naming.virtual_network.name
    virtual_network_unique      = module.azure_naming.virtual_network.name_unique
    subnet                      = module.azure_naming.subnet.name
    subnet_unique               = module.azure_naming.subnet.name_unique
    network_security_group      = module.azure_naming.network_security_group.name
    network_security_group_unique = module.azure_naming.network_security_group.name_unique
    route_table                 = module.azure_naming.route_table.name
    route_table_unique          = module.azure_naming.route_table.name_unique
    public_ip                   = module.azure_naming.public_ip.name
    public_ip_unique            = module.azure_naming.public_ip.name_unique
    network_interface           = module.azure_naming.network_interface.name
    network_interface_unique    = module.azure_naming.network_interface.name_unique
    virtual_machine             = module.azure_naming.virtual_machine.name
    virtual_machine_unique      = module.azure_naming.virtual_machine.name_unique
    storage_account             = module.azure_naming.storage_account.name
    storage_account_unique      = module.azure_naming.storage_account.name_unique
    key_vault                   = module.azure_naming.key_vault.name
    key_vault_unique            = module.azure_naming.key_vault.name_unique
    log_analytics_workspace     = module.azure_naming.log_analytics_workspace.name
    log_analytics_workspace_unique = module.azure_naming.log_analytics_workspace.name_unique
    availability_set            = module.azure_naming.availability_set.name
    availability_set_unique     = module.azure_naming.availability_set.name_unique
    managed_disk                = module.azure_naming.managed_disk.name
    managed_disk_unique         = module.azure_naming.managed_disk.name_unique
    load_balancer               = module.azure_naming.load_balancer.name
    load_balancer_unique        = module.azure_naming.load_balancer.name_unique
    application_gateway         = module.azure_naming.application_gateway.name
    application_gateway_unique  = module.azure_naming.application_gateway.name_unique
  } : {}
}

###############################################################
# OUTPUT: custom_names
# Description: Custom resource names generated by this module
# Structure: Map of custom resource types to their names
# Usage: module.naming.custom_names.palo_alto_vm_series
# Example: "neko-palofw-prod-weu-01"
###############################################################
output "custom_names" {
  description = "Custom resource names generated by this module"
  value       = local.sanitize_name
}

###############################################################
# OUTPUT: all_names
# Description: Combined map of all available resource names
# Structure: Merge of Azure names + custom names
# Usage: module.naming.all_names["resource_type"]
# Benefit: Single source for all naming needs
###############################################################
output "all_names" {
  description = "Combined map of all resource names (Azure module + custom)"
  value       = local.all_names
}

###############################################################
# OUTPUT: storage_names
# Description: Sanitized storage account names
# Structure: Map of storage-related resources to sanitized names
# Usage: module.naming.storage_names["custom_storage"]
# Note: Storage accounts have special naming rules (lowercase, no hyphens, 3-24 chars)
###############################################################
output "storage_names" {
  description = "Sanitized storage account names (lowercase, alphanumeric only, max 24 chars)"
  value       = local.storage_names
}

###############################################################
# OUTPUT: palo_alto_names
# Description: Palo Alto specific resource names
# Structure: Map of Palo Alto resources to their names
# Usage: module.naming.palo_alto_names.vm_series
# Convenience output for Palo Alto deployments
###############################################################
output "palo_alto_names" {
  description = "Palo Alto Networks specific resource names"
  value = {
    vm_series          = lookup(local.sanitize_name, "palo_alto_vm_series", null)
    management_profile = lookup(local.sanitize_name, "palo_alto_management_profile", null)
    interface          = lookup(local.sanitize_name, "palo_alto_interface", null)
    zone               = lookup(local.sanitize_name, "palo_alto_zone", null)
    virtual_router     = lookup(local.sanitize_name, "palo_alto_virtual_router", null)
    security_policy    = lookup(local.sanitize_name, "palo_alto_security_policy", null)
  }
}

###############################################################
# OUTPUT: naming_components
# Description: Individual naming components used in generation
# Structure: Map of components (prefix, suffix, environment, region)
# Usage: For documentation or debugging naming logic
###############################################################
output "naming_components" {
  description = "Individual naming components used in name generation"
  value = {
    prefix      = var.prefix
    suffix      = var.suffix
    environment = var.environment
    region      = var.region
    unique_seed = var.unique_seed
  }
}

###############################################################
# OUTPUT: built_names
# Description: Pre-built resource names with all suffixes
# Structure: Nested map { resource_type => { suffix => name } }
# Usage: module.naming.built_names.palo_alto_interface["trust"]
# Example: "neko-paloif-trust-prod-weu-01"
# Use Case: When you need multiple variations of a resource name
###############################################################
output "built_names" {
  description = "Pre-built resource names with all name_suffixes applied"
  value       = local.build_name
}

###############################################################
# OUTPUT: validation_result
# Description: Result of naming validation
# Value: true if all validations passed
# Usage: Check if naming configuration is valid
###############################################################
output "validation_result" {
  description = "Result of naming validation (true if all validations passed)"
  value       = var.validate_names ? true : null
}

###############################################################
# CONVENIENCE OUTPUTS
# Description: Direct access to commonly used names
###############################################################

# Resource Group names
output "resource_group_name" {
  description = "Generated resource group name"
  value       = var.use_azure_naming_module ? module.azure_naming.resource_group.name : lookup(local.sanitize_name, "resource_group", null)
}

# Virtual Network names
output "virtual_network_name" {
  description = "Generated virtual network name"
  value       = var.use_azure_naming_module ? module.azure_naming.virtual_network.name : lookup(local.sanitize_name, "virtual_network", null)
}

# Subnet names
output "subnet_name" {
  description = "Generated subnet name"
  value       = var.use_azure_naming_module ? module.azure_naming.subnet.name : lookup(local.sanitize_name, "subnet", null)
}

# NSG names
output "network_security_group_name" {
  description = "Generated network security group name"
  value       = var.use_azure_naming_module ? module.azure_naming.network_security_group.name : lookup(local.sanitize_name, "network_security_group", null)
}

# Route Table names
output "route_table_name" {
  description = "Generated route table name"
  value       = var.use_azure_naming_module ? module.azure_naming.route_table.name : lookup(local.sanitize_name, "route_table", null)
}

# Public IP names
output "public_ip_name" {
  description = "Generated public IP name"
  value       = var.use_azure_naming_module ? module.azure_naming.public_ip.name : lookup(local.sanitize_name, "public_ip", null)
}

# VM names
output "virtual_machine_name" {
  description = "Generated virtual machine name"
  value       = var.use_azure_naming_module ? module.azure_naming.virtual_machine.name : lookup(local.sanitize_name, "virtual_machine", null)
}

# Storage Account names
output "storage_account_name" {
  description = "Generated storage account name (sanitized for storage account requirements)"
  value       = var.use_azure_naming_module ? module.azure_naming.storage_account.name_unique : lookup(local.storage_names, "storage_account", null)
}

# Key Vault names
output "key_vault_name" {
  description = "Generated key vault name"
  value       = var.use_azure_naming_module ? module.azure_naming.key_vault.name_unique : lookup(local.sanitize_name, "key_vault", null)
}

# Palo Alto VM Series name
output "palo_alto_vm_name" {
  description = "Generated Palo Alto VM Series name"
  value       = lookup(local.sanitize_name, "palo_alto_vm_series", null)
}
