###############################################################
# VARIABLE: prefix
# Type: string (optional)
# Default: null
# Description: Prefix to add to all resource names
# Example: "neko", "mycompany", "project"
# Azure Naming Module: Passed through to official module
###############################################################
variable "prefix" {
  description = "Prefix to add to all resource names (e.g., company name, project name)"
  type        = string
  default     = null

  validation {
    condition     = var.prefix == null || length(var.prefix) <= 10
    error_message = "Prefix should not exceed 10 characters to avoid name length issues."
  }
}

###############################################################
# VARIABLE: suffix
# Type: string (optional)
# Default: null
# Description: Suffix to add to all resource names
# Example: "01", "001", "prod"
# Azure Naming Module: Passed through to official module
###############################################################
variable "suffix" {
  description = "Suffix to add to all resource names (e.g., instance number, index)"
  type        = string
  default     = null

  validation {
    condition     = var.suffix == null || length(var.suffix) <= 10
    error_message = "Suffix should not exceed 10 characters to avoid name length issues."
  }
}

###############################################################
# VARIABLE: environment
# Type: string (optional)
# Default: null
# Description: Environment name (dev, staging, prod, etc.)
# Used in custom naming: {prefix}-{resource}-{name}-{environment}-{region}-{suffix}
###############################################################
variable "environment" {
  description = "Environment name to include in resource names (dev, staging, prod, etc.)"
  type        = string
  default     = null

  validation {
    condition = var.environment == null || contains(
      ["dev", "test", "staging", "uat", "prod", "dr", "sandbox", "lab"],
      var.environment
    )
    error_message = "Environment must be one of: dev, test, staging, uat, prod, dr, sandbox, lab."
  }
}

###############################################################
# VARIABLE: region
# Type: string (optional)
# Default: null
# Description: Azure region short name
# Examples: "weu" (West Europe), "eus" (East US), "frc" (France Central)
# Used in custom naming for geo-location identification
###############################################################
variable "region" {
  description = "Azure region short name for resource naming (e.g., weu, eus, frc)"
  type        = string
  default     = null

  validation {
    condition     = var.region == null || length(var.region) <= 5
    error_message = "Region code should not exceed 5 characters."
  }
}

###############################################################
# VARIABLE: unique_seed
# Type: string (optional)
# Default: ""
# Description: Seed for generating unique names in Azure naming module
# Azure Naming Module: Used to generate unique suffixes
# Use Case: Ensure globally unique names for storage accounts, key vaults
###############################################################
variable "unique_seed" {
  description = "Unique seed for generating unique resource names (passed to Azure naming module)"
  type        = string
  default     = ""
}

###############################################################
# VARIABLE: unique_length
# Type: number (optional)
# Default: 4
# Description: Length of unique suffix generated by Azure naming module
# Azure Naming Module: Controls suffix length
# Range: 1-8 characters
###############################################################
variable "unique_length" {
  description = "Length of unique suffix for resource names (1-8 characters)"
  type        = number
  default     = 4

  validation {
    condition     = var.unique_length >= 1 && var.unique_length <= 8
    error_message = "unique_length must be between 1 and 8."
  }
}

###############################################################
# VARIABLE: custom_resource_types
# Type: map(string) (optional)
# Default: {} (empty map, uses built-in types)
# Description: Additional custom resource types to support
# Structure: { resource_type_name = "short_name" }
# Use Case: Extend naming for resources not in Azure module
# Example:
# {
#   "my_custom_app" = "app"
#   "my_custom_db"  = "db"
# }
# Result: "prefix-app-name-env-region-suffix"
###############################################################
variable "custom_resource_types" {
  description = "Map of custom resource types to their short names for naming convention"
  type        = map(string)
  default     = {}

  validation {
    condition = alltrue([
      for k, v in var.custom_resource_types :
      length(v) >= 2 && length(v) <= 10
    ])
    error_message = "Custom resource type short names must be between 2 and 10 characters."
  }
}

###############################################################
# VARIABLE: name_suffixes
# Type: list(string) (optional)
# Default: [] (empty list)
# Description: List of name suffixes for building multiple resource names
# Use Case: Generate multiple variations of a resource name
# Example: ["trust", "untrust", "mgmt"] for Palo Alto interfaces
# Result with build_name:
#   - "prefix-paloif-trust-env-region-suffix"
#   - "prefix-paloif-untrust-env-region-suffix"
#   - "prefix-paloif-mgmt-env-region-suffix"
###############################################################
variable "name_suffixes" {
  description = "List of name suffixes for building multiple resource name variations"
  type        = list(string)
  default     = []
}

###############################################################
# VARIABLE: validate_names
# Type: bool (optional)
# Default: true
# Description: Enable validation of naming inputs
# Use Case: Disable for testing or when validation is too strict
###############################################################
variable "validate_names" {
  description = "Enable validation of naming convention inputs"
  type        = bool
  default     = true
}

###############################################################
# VARIABLE: use_azure_naming_module
# Type: bool (optional)
# Default: true
# Description: Whether to use Azure official naming module
# Use Case: Disable to use only custom naming logic
###############################################################
variable "use_azure_naming_module" {
  description = "Use Azure official naming module for standard resources"
  type        = bool
  default     = true
}

###############################################################
# VARIABLE: naming_convention_format
# Type: string (optional)
# Default: "prefix-type-name-env-region-suffix"
# Description: Custom naming convention format
# Supported placeholders:
#   - {prefix}: var.prefix
#   - {type}: resource type short name
#   - {name}: specific resource name
#   - {env}: var.environment
#   - {region}: var.region
#   - {suffix}: var.suffix
# Example: "{prefix}-{type}-{env}-{region}-{name}-{suffix}"
###############################################################
variable "naming_convention_format" {
  description = "Custom naming convention format (use {prefix}, {type}, {name}, {env}, {region}, {suffix} placeholders)"
  type        = string
  default     = "{prefix}-{type}-{name}-{env}-{region}-{suffix}"

  validation {
    condition     = can(regex("\\{type\\}", var.naming_convention_format))
    error_message = "Naming convention format must include {type} placeholder."
  }
}
